sudo: required
services:
 - docker

before_install:
 - docker build -t mytestimage -f Dockerfile.dev .

script:
 - docker run -e CI=true mytestimage npm run test
 
before_deploy:
  - rvm 1.9.3 do gem install aws-sdk -v 2.1.36

deploy:
 provider: elasticbeanstalk
 region: "eu-west-2"
 app: "docker-reactapp"
 env: "DockerReactapp-env-1"
 bucket_name: "elasticbeanstalk-eu-west-2-217456606433"
 bucket_path: "docker-reactapp"
 skip_cleanup: true
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
  secure: $AWS_SECRET_ACCESS_KEY
